### ISSUE TITLE
什么是文档流，该怎么回答呢

### ISSUE THREAD

**Issue by Zn139** [57code/vue-interview#2]

**Comment by 57code** [comment]
感谢提问，这个问题不属于vue范畴。就不往项目中合并了。

文档流的翻译容易误导人，原文是"normal flow"，被翻译成文档流容易误解，也有人叫普通流、正常流，指语言文本从左到右，从上到下显示，这是传统HTML文档的文本布局。浮动(float)、绝对定位(absolute)、固定定位(fixed)三种方式定位会脱离文档流。

文档流是相对于盒子模型讲的文本流是相对于文子段落讲的元素浮动之后，会让它跳出文档流，也就是说当它后面还有元素时，其他元素会无视它所占据了的区域，直接在它身下布局。但是文字却会认同浮动元素所占据的区域，围绕它布局，也就是没有拖出文本流。但是绝对定位后，不仅元素盒子会拖出文档流，文字也会出文本流。那么后面元素的文本就不会在认同它的区域位置，会直接在它后面布局，不会在环绕。当然你可以使用 index-z 来让底部的元素到上面来，类似于一个图层的概念
