### ISSUE TITLE
v-if v-for执行优先级。村长你的这个有错吧？

### ISSUE THREAD

**Issue by coderzhongkaikai** [57code/vue-interview#5]

**Comment by codersjj** [comment]
> <img alt="image" width="1016" src="https://user-images.githubusercontent.com/51220436/167378363-fe597a32-d1c1-43ac-8ad3-f5531c568cc1.png">
> 
> 、

这里应该是村长还没把 `Vue 3` 的内容更新进来，在 `Vue 2` 中，确实是 `v-for` 的优先级高于 `v-if`，但到了 `Vue 3` 中，则是 `v-if` 的优先级高于 `v-for` 了。你也可以看下村长的[视频](https://www.bilibili.com/video/BV1SL4y1L79x/?spm_id_from=333.788)，里面有说到的。

**Comment by 57code** [comment]
我讲题目的视频是按vue2和vue3来的，这里忘了更新，感谢大家提醒
